stages:
  - install
  - test
  - build
  - deploy

before_script:
  # Install yarn as outlined in (https://yarnpkg.com/lang/en/docs/install/#alternatives-stable)
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  # Make available in the current terminal
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

cache:
  paths:
    - node_modules/
    - .yarn

install:
  stage: install
  image: node
  script:
    - echo "Start to install dependencies"
    - yarn
    - echo "install successfully!"

build:
  stage: build
  image: node
  cache:
    paths:
      - node_modules/
      - .yarn
  script:
    - echo "Start building App"
    - yarn build
    - echo "Build successfully!"
  artifacts:
    expire_in: 1 hour
    paths:
      - build
      - node_modules/

test:
  stage: test
  cache:
    paths:
      - node_modules/
      - .yarn
  image: node
  script:
    - echo "Testing App"
    - yarn
    - CI=true yarn test
    - echo "Test successfully!"

deploy:
  stage: deploy
  image: node
  only:
    - develop
    - staging
  dependencies:
    - install
    - build
  before_script:
    - yarn global add firebase-tools
    - yarn build
  cache:
    paths:
      - node_modules/
      - build/
  script:
    - firebase deploy --token $FIREBASE_DEPLOY_TOKEN --only hosting:adams-dev

